coco_dataset_dir: '/home/jack/Documents/Workspace/kumu/compiled_v13'
mlflow:
  tracking_uri: "http://internal.ainascan.com:30520"
  experiment_name: "Laau Leaf Instance Segmentation"
  run_description: "Laau Leaf Instance Segmentation with modified anchor ratios and sizes and fixed min/max sizes."
  tags:
    - name: dataset
      value: compiled_v13
detectron:
  model_arch: 'COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml'
  model_weights: 'https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl'
  score_thresh_test: 0.7
  nms_thresh_test: 0.5
  batch_size_per_image: 64
  number_of_classes: 1
  freeze_at: 2
  crop_enabled: False
  random_flip: "none"
  checkpoint_period: 1000
  max_size_train: 1920
  max_size_test: 1920
  min_size_train: [1080]
  min_size_test: 1080
  epochs: 2000
  batch_size: 4
  base_learning_rate: 0.0005
  eval_period: 250
  anchor_ratios: [[0.7, 1.5, 2.2]]
  anchor_sizes: [[64, 128, 256, 512, 640]]
